package com.jtomaszk.apps.common.chart;

import android.graphics.Color;

import com.google.common.collect.Lists;

import java.util.List;

import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;

/**
 * Created by jtomaszk on 15.12.15.
 */
public class DataChartBuilder {
    private List<Line> lines = Lists.newArrayList();
    private Axis axisX;
    private Axis axisY;

    public DataChartBuilder() {
    }

    public DataChartBuilder addLine(List<ChartPoint> list) {
        List<PointValue> values = Lists.newArrayList();

        for (ChartPoint entry : list) {
            values.add(new PointValue(entry.getX(), entry.getY()));
        }

        Line line = new Line(values).setColor(Color.BLUE).setCubic(true).setHasPoints(true);
        lines.add(line);
        return this;
    }

    public DataChartBuilder addAxisX() {
        return addAxisX(null);
    }

    public DataChartBuilder addAxisX(AxisValueFormatter formatter) {
        axisX = new Axis()
                .setAutoGenerated(true)
                .setFormatter(formatter);
        return this;
    }

    public DataChartBuilder addAxisY() {
        axisY = new Axis()
                .setAutoGenerated(true)
                .setHasSeparationLine(true);
        return this;
    }

    public LineChartData getData() {
        LineChartData data = new LineChartData();
        data.setLines(lines);
        data.setAxisYLeft(axisY);
        data.setAxisXBottom(axisX);
        return data;
    }

}
